# 赞助链接（可选）
# github: [your-username]
# patreon: your-patreon
# ko_fi: your-ko-fi
custom: ['https://siusn-sisjxl.top/#/register?code=aVDxxRS0', 'https://dashboard.thordata.com/zh/isp-proxies/proxy-list']

